[package]
name = "caeles-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasmtime = "29"
<<<<<<< Updated upstream
reqwest = { version = "0.11", features = ["blocking"] }
=======
once_cell = "1"
toml = "0.8"
dirs = "5"
>>>>>>> Stashed changes
